---
- name: Create EC2 Instance
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Launch EC2 Instance
      ec2:
        key_name: my-key-pair  # Change this to your key pair name
        instance_type: t2.micro  # Specify the instance type
        image: ami-0c55b159cbfafe1f0  # Change to a valid AMI ID for your region
        wait: yes
        count: 1
        region: us-west-2  # Change to your preferred region
        group: my-security-group  # Change to your security group name
        instance_tags:
          Name: MyEC2Instance  # Tag the instance
      register: ec2

    - name: Show instance details
      debug:
        var: ec2

