---
- name: Run Terraform to provision resources
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Initialize Terraform
      command: terraform init
      args:
        chdir: /var/lib/awx/projects/_16__ansible_awx/ansible_awx  # Correct path to your Terraform files

    - name: Apply Terraform configuration
      command: terraform apply -auto-approve
      args:
        chdir: /var/lib/awx/projects/_16__ansible_awx/ansible_awx  # Correct path to your Terraform files

    - name: Terraform Output
      command: terraform output
      args:
        chdir: /var/lib/awx/projects/_16__ansible_awx/ansible_awx  # Correct path to your Terraform files
      register: output

    - name: Display Terraform Output
      debug:
        var: output.stdout_lines
